### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Tsunami_Simulator)
add_subdirectory(Tsunami_SimulatorContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Tsunami_Simulatorplugin
    Tsunami_SimulatorContentplugin
    QtQuickDesignerComponents)